#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh"
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/mptcp/arch/sim/test/buildtop/build/lib
 export PATH=$PATH:/root/mptcp/arch/sim/test/buildtop/build/bin
 export PYTHONPATH=$PYTHONPATH:/root/mptcp/arch/sim/test/bake:/root/mptcp/arch/sim/test/buildtop/build/lib:/root/mptcp/arch/sim/test/buildtop/build/lib/python2.7/dist-packages
 export INSTALL_BASE=/root/mptcp/arch/sim/test/buildtop/build
