# CMake generated Testfile for 
# Source directory: /home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/Testing
# Build directory: /home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/Testing
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(gxConfiguration.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxConfiguration.cxx" "-fxml=gxConfiguration.cxx.gcc.xml")
ADD_TEST(gxConfiguration.h "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxConfiguration.h" "-fxml=gxConfiguration.h.gcc.xml")
ADD_TEST(gxDocumentation.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxDocumentation.cxx" "-fxml=gxDocumentation.cxx.gcc.xml")
ADD_TEST(gxDocumentation.h "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxDocumentation.h" "-fxml=gxDocumentation.h.gcc.xml")
ADD_TEST(gxFlagsParser.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxFlagsParser.cxx" "-fxml=gxFlagsParser.cxx.gcc.xml")
ADD_TEST(gxFlagsParser.h "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxFlagsParser.h" "-fxml=gxFlagsParser.h.gcc.xml")
ADD_TEST(gxFront.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxFront.cxx" "-fxml=gxFront.cxx.gcc.xml")
ADD_TEST(gxSystemTools.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxSystemTools.cxx" "-fxml=gxSystemTools.cxx.gcc.xml")
ADD_TEST(gxSystemTools.h "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront/gxSystemTools.h" "-fxml=gxSystemTools.h.gcc.xml")
ADD_TEST(TestFullPathInclude.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/Testing/TestFullPathInclude.cxx" "-fxml=TestFullPathInclude.cxx.gcc.xml")
ADD_TEST(TestUsualInclude.cxx "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/bin/gccxml" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML/GXFront" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/objdir/GCC_XML" "-I/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/GXFront" "/home/dkoe/mptcp/arch/sim/test/buildtop/source/gccxml/GCC_XML/Testing/TestUsualInclude.cxx" "-fxml=TestUsualInclude.cxx.gcc.xml")
