/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.14";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/root/mptcp/arch/sim/test/buildtop/build/etc/wgetrc\" -DLOCALEDIR=\"/root/mptcp/arch/sim/test/buildtop/build/share/locale\" -I. -I../lib -I../lib -fPIC -g";
const char *link_string = "gcc -fPIC -g -pie -rdynamic -lpcre -lrt ../lib/libgnu.a";
